name: Report something is not working properly 🐛
description: Use this if there is something that is not working properly.  If you are not sure or you need help making something work, please ask a question instead.
labels: part:❓, priority:❓, type:bug
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Please tell us what happen that it shouldn't have.
      placeholder: What happen that it shouldn't have.
    validations:
      required: true
  - type: textarea
    id: what-expected
    attributes:
      label: What did you expected instead?
      description: Please tell us what did you expect to happen.
      placeholder: What did you expect to happen.
    validations:
      required: true
  - type: dropdown
    id: version
    attributes:
      label: Version
      description: What version of our software are you running?
      options:
        - 1.0.2
        - 1.0.3
    validations:
      required: true
  - type: dropdown
    id: arch
    attributes:
      label: What architecture are you seeing the problem on?
      multiple: true
      options:
        - x86_64
        - amr64
        - unknown
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://example.com)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
  - type: markdown
    attributes:
      value: <!-- form-version:v1.0.0 -->
