blank_issues_enabled: true
contact_links:
  - name: Ask a question ❓
    url: https://github.com/frequenz-floss/demo/discussions
    about: Use this if you are not sure how to do something, have installation problems, etc.
